### ISSUE TITLE
backend dependency not available

### ISSUE THREAD

**Issue by RahulRupani8** [canscale/supernova-candb-demo#1]
Couldn't find the candb dependency mentioned in the package-set.dhall in the backend directory , This is the repo https://github.com/canscale/candb which is isn't available..

**Comment by ByronBecker** [comment]
@RahulRupani8 Thanks for opening this issue! 

The CanDB repositories do exist, but they are currently private, which is why you are currently unable to fully build the Supernova application.

This is because CanDB is currently in a closed alpha, through which I'm collaborating with over 15 projects to gather feedback in order to fix bugs and further refine the API before releasing CanDB publicly (hopefully late Q4 this year).

If you're interested in becoming an alpha participant, I recommend first watching the Supernova demo video https://www.youtube.com/watch?v=QSwwMRoPF0M and then reaching out to me via one of the avenues listed in the video if you think your project is a good fit.

**Comment by RahulRupani8** [comment]
Thanks for your response, I'll surely get back to you as soon as possible.
